"""empty message

Revision ID: 0e496c3803c4
Revises: 4af83d017e90
Create Date: 2021-03-24 23:16:14.805939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e496c3803c4'
down_revision = '4af83d017e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('shelfcount', sa.Integer(), nullable=False))
    op.add_column('inventory', sa.Column('shelfid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'shelf', ['shelfid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'shelfid')
    op.drop_column('inventory', 'shelfcount')
    # ### end Alembic commands ###
