"""empty message

Revision ID: 40b624beda7c
Revises: 0e496c3803c4
Create Date: 2021-07-20 01:19:59.712575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b624beda7c'
down_revision = '0e496c3803c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('shelfcount', sa.Integer(), nullable=False),
    sa.Column('storeid', sa.Integer(), nullable=True),
    sa.Column('productid', sa.Integer(), nullable=True),
    sa.Column('shelfid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['productid'], ['product.id'], ),
    sa.ForeignKeyConstraint(['shelfid'], ['shelf.id'], ),
    sa.ForeignKeyConstraint(['storeid'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storeid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shelfcount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shelfid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['productid'], ['product.id'], name='inventory_productid_fkey'),
    sa.ForeignKeyConstraint(['shelfid'], ['shelf.id'], name='inventory_shelfid_fkey'),
    sa.ForeignKeyConstraint(['storeid'], ['store.id'], name='inventory_storeid_fkey'),
    sa.PrimaryKeyConstraint('id', name='inventory_pkey')
    )
    op.drop_table('order')
    # ### end Alembic commands ###
