"""empty message

Revision ID: 7620d7916bd1
Revises: 
Create Date: 2021-03-24 17:52:19.702387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7620d7916bd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('latitude', sa.String(length=100), nullable=True),
    sa.Column('longitude', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('storeid', sa.Integer(), nullable=True),
    sa.Column('productid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['productid'], ['product.id'], ),
    sa.ForeignKeyConstraint(['storeid'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('store')
    op.drop_table('product')
    # ### end Alembic commands ###
